source/accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view, register_view, UserDetailView, UserPersonalInfoChangeView, \
    UserPasswordChangeView, AllUsersView


urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("create", register_view, name="create"),
    path("<int:pk>/", UserDetailView.as_view(), name="detail"),
    path("<int:pk>/update", UserPersonalInfoChangeView.as_view(), name="update"),
    path("<int:pk>/change_password", UserPasswordChangeView.as_view(), name="change_password"),
    path('all/', AllUsersView.as_view(), name="users")

]

app_name = "accounts"

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("webapp.urls"))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.contrib import admin
from django.urls import path
from webapp.views import IndexView, IssueView, IssueUpdateView, IssueCreateView, IssueDeleteView, StatusView, \
    TypeView, StatusCreateView, TypeCreateView, StatusUpdateView, TypeUpdateView, TypeDeleteView, StatusDeleteView,\
    ProjectView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView, ProjectDetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path('issue/<int:pk>/', IssueView.as_view(), name='issue_view'),
    path("issue/add/", IssueCreateView.as_view(), name="issue_add"),
    path('issue/<int:pk>/edit/', IssueUpdateView.as_view(), name='issue_update'),
    path("issue/<int:pk>/delete", IssueDeleteView.as_view(), name="issue_delete"),
    path("statuses/all", StatusView.as_view(), name="all_statuses"),
    path("statuses/add/", StatusCreateView.as_view(), name="status_add"),
    path('statuses/<int:pk>/edit/', StatusUpdateView.as_view(), name="status_update"),
    path("types/all", TypeView.as_view(), name="all_types"),
    path("types/add", TypeCreateView.as_view(), name="type_add"),
    path("types/<int:pk>/edit/", TypeUpdateView.as_view(), name="type_update"),
    path('statuses/<int:pk>/delete/', StatusDeleteView.as_view(), name="status_delete"),
    path('types/<int:pk>/delete/', TypeDeleteView.as_view(), name="type_delete"),
    path("projects/all", ProjectView.as_view(), name="all_projects"),
    path("projects/<int:pk>", ProjectDetailView.as_view(), name="project_view"),
    path("projects/add", ProjectCreateView.as_view(), name="project_add"),
    path("projects/<int:pk>/edit/", ProjectUpdateView.as_view(), name="project_update"),
    path("projects/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project_delete")
]

app_name = "webapp"

source/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):

    DEFAULT_AVATAR = "/uploads/user_pics/default_avatar.jpg"

    user = models.OneToOneField(User, related_name="profile", on_delete=models.CASCADE, verbose_name="Пользователь")
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name="Аватар")
    about = models.TextField(max_length=3000, null=True, blank=True, verbose_name="О себе")
    github = models.URLField(null=True, blank=True, verbose_name="Профиль Github")

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"


class Team(models.Model):
    user = models.ForeignKey(User, related_name="teams", on_delete=models.CASCADE, verbose_name='Юзер')
    project = models.ForeignKey("webapp.Project", related_name="teams", on_delete=models.CASCADE,
                                verbose_name='Проект')
    start_date = models.DateTimeField(verbose_name="Start date")
    end_date = models.DateTimeField(verbose_name="End created")

source/accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError


class UserCreationForm(forms.ModelForm):
    username = forms.CharField(max_length=100, label="Username", required=True)
    password = forms.CharField(max_length=100, label="Password", required=True, widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, label="Confirm Password", required=True,
                                       widget=forms.PasswordInput)
    email = forms.EmailField(label='Email', required=True)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            User.objects.get(username=username)
            raise ValidationError("User with this username already exists", code="username_exists")

        except User.DoesNotExist:
            return username

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data['password']
        password_2 = self.cleaned_data["password_confirm"]
        data = self.cleaned_data
        if not data.get('first_name') and not data.get('last_name'):
            raise ValidationError("One of the following fields: first_name, last_name should be filled",
                                  code='first_name_last_name_criteria_empty')
        if password_1 != password_2:
            raise ValidationError("Passwords does not match", code="passwords_does_not_match")
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
            raise ValidationError('User with this email already exists', code='user_email_exists')
        except User.DoesNotExist:
            return email

    class Meta:
        model = User
        fields = ['username', 'password', "password_confirm", 'first_name', 'last_name', 'email']


class UserChangeForm(forms.ModelForm):
    avatar = forms.ImageField(label="Аватар", required=False)
    about = forms.CharField(widget=forms.Textarea, label="О себе", required=False)
    github = forms.URLField(label="Github", required=False)

    class Meta:
        model = User
        fields = ["first_name", 'last_name', 'email', 'avatar', 'about', 'github']
        profile_fields = ['avatar', 'about', 'github']
        labels = {'first_name': "Имя", "last_name": "Фамилия", "email": "email"}

    def save(self, commit=True):
        user = super().save(commit)
        self.save_profile(commit)
        return user

    def save_profile(self, commit=True):
        profile = self.instance.profile

        for field in self.Meta.profile_fields:
            setattr(profile, field, self.cleaned_data[field])

        if not profile.avatar:
            profile.avatar = None

        if commit:
            profile.save()

    def get_initial_for_field(self, field, field_name):
        if field_name in self.Meta.profile_fields:
            return getattr(self.instance.profile, field_name)
        return super().get_initial_for_field(field, field_name)

    def clean_github(self):
        github = self.cleaned_data.get("github")
        if github.startswith("https://github.com/"):
            git_name = github.replace("https://github.com/", "")
            git_name = git_name.rstrip("/")
            if len(git_name) > 39:
                raise ValidationError('Github username maximum is 39 characters', code='git_name_more_than_39')
            elif git_name.startswith("-") or git_name.endswith:
                raise ValidationError("Github username can't starts or ends with hyphen",
                                      code='git_name_starts_or_ends_with_hyphen')
            elif "--" in git_name:
                raise ValidationError("Github username can't have multiple consecutive hyphen",
                                      code='git_name_multiple_hyphen')
            elif not git_name.replace("-", "").isalnum():
                raise ValidationError("Github username may only contain alphanumeric characters or hyphens",
                                      code='git_name_unacceptable_symbols')
            return self.cleaned_data
        else:
            raise ValidationError('It is not a link to github profile', code='wrong_github_link')


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="New password", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Confirm password", strip=False, widget=forms.PasswordInput)
    old_password = forms.CharField(label="Old password", strip=False, widget=forms.PasswordInput)

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        user = self.instance
        if not user.check_password(old_password):
            raise ValidationError('Invalid password.', code='invalid_password')
        return old_password

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Passwords do not match", code='passwords_do_not_match')


    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, ListView
from accounts.models import Profile
from .forms import UserCreationForm, UserChangeForm, PasswordChangeForm


def login_view(request):
    context = {}
    next_page = request.GET.get('next')
    redirect_page = request.session.setdefault('redirect_page', next_page)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            if next_page:
                return redirect(redirect_page)
            return redirect('webapp:index')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:index')


def register_view(request):
    if request.method == "GET":
        form = UserCreationForm()
        return render(request, "user_create.html", {"form": form})
    elif request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = User(username=form.cleaned_data["username"])
            user.set_password(form.cleaned_data["password"])
            user.save()
            Profile.objects.create(user=user)
            login(request, user)
            return redirect('webapp:index')
        else:
            return render(request, "user_create.html", {"form": form})


class UserDetailView(DetailView):
    model = User
    template_name = "user_detail.html"
    context_object_name = "user_obj"


class UserPersonalInfoChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = "user_update.html"
    form_class = UserChangeForm
    context_object_name = "user_obj"

    def test_func(self):
        return self.request.user.pk == self.kwargs["pk"]

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = "user_change_password.html"
    form_class = PasswordChangeForm
    context_object_name = "user_obj"

    def test_func(self):
        return self.request.user.pk == self.kwargs["pk"]

    def get_success_url(self):
        return reverse("accounts:login")


class AllUsersView(ListView):
    template_name = "all_users.html"
    context_object_name = "users"
    paginate_by = 20
    paginate_orphans = 2

    def get_queryset(self):
        return User.objects.all().order_by("username")

source/accounts/templates/all_users.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <h1>Users:</h1>
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
        <hr/>
        {% for user in users %}
            <h2><a href="{% url 'accounts:detail' user.pk %}">{{ user.username }}</a></h2>
        {% endfor %}
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
    </section>
{% endblock %}

source/accounts/templates/login.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
         content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Вход</title>
</head>
<body>
<div class="container">
    <h1>Вход</h1>
    <form action="{% url 'accounts:login' %}?next={{ next }}" method="post" class="text-center">
        {% csrf_token %}
        <input type="hidden" name="next" value=" {{ next }}">
        {% if has_error %}
            <p class="form-error">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" name="username" id="username" value=" {{ username }}">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" name="password" id="password">
        </div>
        <button type="submit">Войти</button>
    </form>
    <p class="text-center"><a href="{% url "webapp:index" %}">На главную</a></p>
</div>

</body>
</html>

source/accounts/templates/user_change_password.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url 'accounts:detail' user_obj.pk %}">View</a></li>
        <li><a href="{% url 'accounts:update' user_obj.pk %}">Edit Profile</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Change password</h1>
    <form action="{% url 'accounts:change_password' user_obj.pk %}" method="post">
        {% include 'partial/form.html' with button_text="Change" %}
    </form>
{% endblock %}

source/accounts/templates/user_create.html
{% extends "base.html" %}

{% block content %}
    <h1>Sing Up</h1>
    <form action="{% url "accounts:create" %}" method="post">
    {% include "partial/form.html" with button_text="Сохранить"%}
    </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends "base.html" %}
{% block title %} User {% endblock %}
{% block menu_links %}
    {% if user_obj == request.user %}
    <li><a href="{% url "accounts:update" user_obj.pk %}">Edit Profile</a></li>
    <li><a href="{% url "accounts:change_password" user_obj.pk %}">Change password</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    {% if user_obj.profile.avatar %}
        <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250" height="250" alt="user picture">
    {% else %}
        <img class="avatar" src="{{ user_obj.profile.DEFAULT_AVATAR }}" width="250" height="250" alt="user picture">
    {% endif %}
    <h1>Profile: {{ user_obj.username }}</h1>
    <p>First name: {{ user_obj.first_name }}</p>
    <p>Last name: {{ user_obj.last_name }}</p>
    <p>email: {{ user_obj.email }}</p>
    <p>about: {{ user_obj.profile.about }}</p>
    <p>github: {{ user_obj.profile.github }}</p>
{% endblock %}

source/accounts/templates/user_update.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url 'accounts:detail' user_obj.pk %}">View</a></li>
        <li><a href="{% url "accounts:change_password" user_obj.pk %}">Change Password</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Edit Profile: {{ user_obj.username }}</h1>
    <form action="{% url 'accounts:update' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text="Update" %}
    </form>
{% endblock %}